import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Explicit list rather than {type: 'autogenerated', dirName: '.'} — an
  // autogenerated sidebar recurses into docs/terms/ and would pull all term
  // pages into this same sidebar as a 70+ item nested category. Term pages
  // opt out of navigation entirely via `displayed_sidebar: null`.
  //
  // Mirrors scripts/lint.ts's SECTIONS list (the six settled sections); not
  // imported from there since lint.ts is out of scope for changes here.
  // Adding a section means updating both.
  glossarySidebar: [
    'index',
    'building-ops',
    'business-strategy',
    'culture-vibes',
    'model-behavior',
    'prompting-context',
    'security-trust',
  ],
};

export default sidebars;
